#!/usr/bin/env python3
"""
analyze_football.py — era, efficiency, schedule, situational, recruiting and luck
analysis for Oklahoma football 1999-2025. Reads football/data/*.csv only (no network),
writes football/data/football_analysis_output.md and charts 01-08. Deterministic.

Questions (see football/report/OKLAHOMA_FOOTBALL_ERAS_REPORT.md):
  Q1 era comparison            Q5 situational splits
  Q2 efficiency (SP+/ESPN)     Q6 recruiting vs results (lagged)
  Q3 SEC transition            Q7 luck vs skill (Pythagorean, one-score, regression)
  Q4 game-level drivers (limited to what the fallback data contains; box-score
     drivers such as turnovers/3rd-down are NOT_AVAILABLE without a CFBD key)
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from scipy import stats  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))
import football_lib as fl  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent          # football/
DATA, CHARTS = ROOT / "data", ROOT / "charts"
CRIMSON, CREAM, GRAY, DARK, GOLD = "#841617", "#FDF9D8", "#8a8d8f", "#2b2b2b", "#C9A227"
# colour-blind-safe (Okabe-Ito) for non-OU categories
BLUE, ORANGE, GREEN, PURPLE = "#0072B2", "#E69F00", "#009E73", "#CC79A7"
ERA_COLOR = {"Stoops": BLUE, "Riley": ORANGE, "Venables": CRIMSON}
plt.rcParams.update({"figure.dpi": 150, "font.size": 10, "axes.titlesize": 12.5,
                     "axes.titleweight": "bold", "axes.edgecolor": "#cccccc",
                     "axes.grid": True, "grid.color": "#e6e6e6", "grid.linewidth": 0.8,
                     "savefig.bbox": "tight", "savefig.facecolor": "white", "savefig.dpi": 200})
np.random.seed(0)


def footer(fig, txt):
    fig.text(0.5, -0.02, txt, ha="center", fontsize=7.5, color="#666666", style="italic")


def era_vlines(ax):
    for b in fl.ERA_BOUNDARIES:
        ax.axvline(b - 0.5, color=DARK, ls="--", lw=1, alpha=0.6)


def era_shade(ax, seasons):
    lo = min(seasons)
    spans = [("Stoops", max(1999, lo), 2016), ("Riley", 2017, 2021), ("Venables", 2022, max(seasons))]
    for name, a, b in spans:
        ax.axvspan(a - 0.5, b + 0.5, color=ERA_COLOR[name], alpha=0.06)
        ax.text((a + b) / 2, ax.get_ylim()[1], name, ha="center", va="top", fontsize=9,
                color=ERA_COLOR[name], fontweight="bold")


def rec(df):
    w = int((df.result == "W").sum()); l = int((df.result == "L").sum())
    return w, l, (w / (w + l) if (w + l) else float("nan"))


def fmt_rec(df):
    w, l, p = rec(df)
    return f"{w}-{l} ({p:.3f})" if w + l else "—"


def main() -> int:
    seasons = pd.read_csv(DATA / "seasons_football.csv")
    games = pd.read_csv(DATA / "games_football.csv")
    ratings = pd.read_csv(DATA / "ratings_football.csv")
    recruiting = pd.read_csv(DATA / "recruiting_football.csv")
    epa = pd.read_csv(DATA / "epa_football.csv") if (DATA / "epa_football.csv").exists() else None
    coaches = pd.read_csv(DATA / "coaches_football.csv")
    for c in ["opp_rank", "ou_rank"]:
        games[c] = pd.to_numeric(games[c], errors="coerce")
    games["ranked_opp"] = games.opp_rank.notna()
    games["top10_opp"] = games.opp_rank <= 10
    games["post"] = games.game_type != "REG"
    seasons["pythag_w"] = [fl.pythagorean_wins(r.PF, r.PA, r.G) for r in seasons.itertuples()]
    seasons["luck_w"] = seasons.W - seasons.pythag_w
    sr = seasons.merge(ratings, on="season", how="left")
    out = ["# Football Analysis — Computed Output", "",
           "_Generated by `football/scripts/analyze_football.py` from `football/data/*.csv`. "
           "Seasons 1999-2025 (27). Ratings 2005-2025 (21). All derived numbers are ESTIMATED "
           "unless the underlying cell is CONFIRMED; formulas are stated inline._", ""]

    # ------------------------------------------------------------ Q1 eras
    out += ["## Q1 — Era comparison (1999-2025)", "",
            "| Era | Seasons | Record | Win% | Conf | Margin/G | vs AP-ranked | vs AP top-10 | Postseason (bowl/CCG/CFP) | Bowls + CFP only | Conf titles | AP top-10 finishes |",
            "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    era_rows = {}
    for era in fl.ERA_ORDER:
        s = seasons[seasons.era == era]; g = games[games.era == era]
        w, l, p = rec(g)
        cw, cl = s.conf_W.sum(), s.conf_L.sum()
        ap10 = (pd.to_numeric(s.ap_final, errors="coerce") <= 10).sum()
        era_rows[era] = dict(n=len(s), w=w, l=l, p=p, mpg=(g.margin.sum() / len(g)),
                             ranked=fmt_rec(g[g.ranked_opp]), top10=fmt_rec(g[g.top10_opp]),
                             post=fmt_rec(g[g.post]),
                             bowls=fmt_rec(g[g.game_type.isin(["BOWL", "BCS_TITLE", "CFP_SEMI", "CFP_R1"])]),
                             titles=int((s.conf_title == "Y").sum()), ap10=int(ap10))
        r = era_rows[era]
        out.append(f"| {era} | {r['n']} | {w}-{l} | {p:.3f} | {cw}-{cl} | {r['mpg']:+.1f} | {r['ranked']} | "
                   f"{r['top10']} | {r['post']} | {r['bowls']} | {r['titles']} | {r['ap10']} |")
    out.append("")
    out.append("_'Postseason' counts every non-regular-season game, so it includes conference championship "
               "games; the separate column gives the bowl-and-playoff record on its own (Stoops went 7-1 in "
               "Big 12 title games and Riley 4-0, which is the whole difference between the two columns)._")
    out.append("")
    out.append("_Venables era n=4 seasons — small-sample warning applies to every Venables row in this file. "
               "Riley-era seasons sum to 56-10 because the 2021 Alamo Bowl was coached by interim Bob Stoops; "
               "Riley's personal record is 55-10 (coaches_football.csv)._")
    out += ["", "### Season table", "",
            "| Season | Era | W-L | Conf | Margin/G | AP final | SP+ rk | FPI rk | SOS rk (ESPN) | Pythag W | Luck (W − exp) |",
            "|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in sr.itertuples():
        f = lambda v: "—" if pd.isna(v) else f"{int(v)}"
        ap = "NR" if pd.isna(r.ap_final) else f"{int(r.ap_final)}"
        out.append(f"| {r.season} | {r.era} | {r.W}-{r.L} | {r.conf_W}-{r.conf_L} | {r.margin_pg:+.1f} | {ap} | "
                   f"{f(r.sp_rank)} | {f(r.fpi_rank)} | {f(r.sos_rank)} | {r.pythag_w:.1f} | {r.luck_w:+.1f} |")
    out.append("")

    # ------------------------------------------------------------ Q2 efficiency
    rt = sr[sr.season >= 2005].copy()
    out += ["## Q2 — Efficiency by era (SP+ and ESPN efficiency ranks; 2005-2025 only)", "",
            "_SP+ = Connelly's opponent- and tempo-adjusted rating (Football Outsiders archive 2005-18; ESPN 2019+). "
            "ESPN eff = ESPN Power Index efficiency ranks. Pre-2005 seasons are NOT_AVAILABLE for these metrics._", "",
            "| Era (2005+) | n | SP+ overall rk (mean) | SP+ offense rk | SP+ defense rk | ESPN off eff rk | ESPN def eff rk | Best SP+ | Worst SP+ |",
            "|---|---|---|---|---|---|---|---|---|"]
    for era in fl.ERA_ORDER:
        e = rt[rt.era == era]
        out.append(f"| {era} | {len(e)} | {e.sp_rank.mean():.1f} | {e.sp_off_rank.mean():.1f} | {e.sp_def_rank.mean():.1f} | "
                   f"{e.eff_off_rank.mean():.1f} | {e.eff_def_rank.mean():.1f} | #{int(e.sp_rank.min())} ({int(e.loc[e.sp_rank.idxmin(), 'season'])}) "
                   f"| #{int(e.sp_rank.max())} ({int(e.loc[e.sp_rank.idxmax(), 'season'])}) |")
    riley = rt[rt.era == "Riley"]; ven = rt[rt.era == "Venables"]
    out += ["", f"- **Riley offense:** SP+ offense ranks {', '.join(f'#{int(x)}' for x in riley.sp_off_rank)} (2017-21) — "
            f"three straight #1s; ESPN offense-efficiency ranks {', '.join(f'#{int(x)}' for x in riley.eff_off_rank)}.",
            f"- **Riley defense:** SP+ defense ranks {', '.join(f'#{int(x)}' for x in riley.sp_def_rank)} — the 2018 unit (#84) is the worst of any OU season in the window.",
            f"- **Venables defense:** SP+ defense ranks {', '.join(f'#{int(x)}' for x in ven.sp_def_rank)} (2022-25) — monotonic improvement to #4 in 2025; "
            f"ESPN {', '.join(f'#{int(x)}' for x in ven.eff_def_rank)}.",
            f"- **Venables offense:** SP+ offense ranks {', '.join(f'#{int(x)}' for x in ven.sp_off_rank)} — the 2024 offense (#76) and 2025 (#51) are the two worst OU offenses in the 21-season window.",
            ""]

    # ------------------------------------------------------------ Q3 SEC transition
    big3 = sr[sr.season.between(2021, 2023)]; sec = sr[sr.season >= 2024]
    gb = games[games.season.between(2021, 2023)]; gs = games[games.season >= 2024]

    def blk(name, s, g):
        w, l, p = rec(g)
        return (f"| {name} | {len(s)} | {w}-{l} ({p:.3f}) | {s.conf_W.sum()}-{s.conf_L.sum()} | {g.margin.mean():+.1f} | "
                f"{s.sos_rank.mean():.0f} | {g.ranked_opp.mean()*100:.0f}% | {fmt_rec(g[g.ranked_opp])} | {s.fpi.mean():.1f} | "
                f"{s.sp_rank.mean():.1f} | {s.sp_off_rank.mean():.0f} / {s.sp_def_rank.mean():.0f} |")
    out += ["## Q3 — SEC transition: final Big 12 years (2021-23) vs SEC (2024-25)", "",
            "| Window | n | Record | Conf | Margin/G | ESPN SOS rk (mean) | Games vs ranked | vs ranked | FPI (mean) | SP+ rk (mean) | SP+ off / def rk |",
            "|---|---|---|---|---|---|---|---|---|---|---|",
            blk("Big 12 2021-23", big3, gb), blk("SEC 2024-25", sec, gs),
            blk("SEC 2024 only", sr[sr.season == 2024], games[games.season == 2024]),
            blk("SEC 2025 only", sr[sr.season == 2025], games[games.season == 2025]), ""]
    # opponent-adjusted read: FPI is already opponent-adjusted (net points vs avg opponent, neutral field)
    d_sos = sec.sos_rank.mean() - big3.sos_rank.mean()
    d_fpi = sec.fpi.mean() - big3.fpi.mean()
    d_m = gs.margin.mean() - gb.margin.mean()
    out += [f"- **Schedule got harder:** ESPN strength-of-schedule rank moved from a mean of #{big3.sos_rank.mean():.0f} (2021-23) to #{sec.sos_rank.mean():.0f} (2024-25), "
            f"and the share of games against AP-ranked opponents went from {gb.ranked_opp.mean()*100:.0f}% to {gs.ranked_opp.mean()*100:.0f}%. [ESTIMATED from REPORTED ranks]",
            f"- **Raw margin fell {abs(d_m):.1f} pts/G** ({gb.margin.mean():+.1f} → {gs.margin.mean():+.1f}); **opponent-adjusted strength (FPI) fell only {abs(d_fpi):.1f} pts** "
            f"({big3.fpi.mean():.1f} → {sec.fpi.mean():.1f}). Roughly {max(0, 1 - abs(d_fpi)/abs(d_m))*100:.0f}% of the raw-margin drop is schedule, not team. [ESTIMATED]",
            f"- **2024 vs 2025 are different teams:** FPI {float(sr[sr.season==2024].fpi.iloc[0]):.1f} → {float(sr[sr.season==2025].fpi.iloc[0]):.1f}; SP+ #{int(sr[sr.season==2024].sp_rank.iloc[0])} → #{int(sr[sr.season==2025].sp_rank.iloc[0])}; "
            f"record 6-7 → 10-3 with a CFP berth against a top-15 schedule. The 2025 rebound survives schedule adjustment; the 2024 collapse was real (SP+ offense #76).",
            ""]

    # ------------------------------------------------------------ Q4 drivers (limited)
    out += ["## Q4 — Game-level drivers (limited to fallback data)", "",
            "_Turnover margin, penalties, third-down and red-zone rates are **NOT_AVAILABLE** in this build "
            "(they require the CFBD API, for which no key was available). What the game log does contain: "
            "opponent AP rank, site, postseason flag, overtime, one-score flag._", "",
            "| Opponent bucket | Stoops | Riley | Venables | All |", "|---|---|---|---|---|"]
    buckets = [("AP top-10", games.top10_opp), ("AP 11-25", games.ranked_opp & ~games.top10_opp), ("Unranked", ~games.ranked_opp)]
    for name, mask in buckets:
        cells = [fmt_rec(games[mask & (games.era == e)]) for e in fl.ERA_ORDER] + [fmt_rec(games[mask])]
        out.append(f"| {name} | " + " | ".join(cells) + " |")
    # logistic-ish: win prob vs opponent rank bucket and site, via simple contingency
    x = games.copy(); x["ranked"] = x.ranked_opp.astype(int); x["home"] = (x.site == "H").astype(int); x["win"] = (x.result == "W").astype(int)
    ct = x.groupby(["ranked", "home"]).win.agg(win_rate="mean", n="size").reset_index()
    out += ["", "Win rate by (ranked opponent × home site), all eras:", "", "| Ranked opp | Home | Win% | n |", "|---|---|---|---|"]
    for r in ct.itertuples():
        out.append(f"| {'Y' if r.ranked else 'N'} | {'Y' if r.home else 'N'} | {r.win_rate:.3f} | {r.n} |")
    out.append("")

    # ------------------------------------------------------------ Q5 situational
    out += ["## Q5 — Situational splits", "", "| Split | Stoops | Riley | Venables | All |", "|---|---|---|---|---|"]
    games_sorted = games.sort_values(["season", "date"]).reset_index(drop=True)
    games_sorted["prev_loss"] = games_sorted.groupby("season").result.shift(1).eq("L")
    splits = [("Home", games.site == "H"), ("Away", games.site == "A"), ("Neutral (incl. Red River, bowls)", games.site == "N"),
              ("vs Texas (Red River, incl. 2018 CCG)", games.opponent == "Texas"),
              ("vs Oklahoma State (Bedlam, through 2023)", games.opponent == "Oklahoma State"),
              ("One-score games (≤8)", games.one_score == "Y"), ("Overtime", games.overtime == "Y"),
              ("Postseason (bowl/CCG/CFP)", games.post),
              ("Bowls + CFP only (no CCGs)", games.game_type.isin(["BOWL", "BCS_TITLE", "CFP_SEMI", "CFP_R1"])), ("Game after a loss (same season)", games_sorted.prev_loss)]
    for name, mask in splits:
        src = games_sorted if name.startswith("Game after") else games
        cells = [fmt_rec(src[mask & (src.era == e)]) for e in fl.ERA_ORDER] + [fmt_rec(src[mask])]
        out.append(f"| {name} | " + " | ".join(cells) + " |")
    out.append("")

    # ------------------------------------------------------------ Q6 recruiting
    out += ["## Q6 — Recruiting (247 Composite class rank) vs results", ""]
    rr = recruiting[["class_year", "rank_247_composite"]].astype({"rank_247_composite": float})
    q6 = sr.copy()
    for lag in (2, 3):
        q6 = fl.lag_join(q6, rr, lag)
    q6["ap_num"] = pd.to_numeric(q6.ap_final, errors="coerce")
    res_rows = []
    for lag in (2, 3):
        col = f"rank_247_composite_lag{lag}"
        d = q6.dropna(subset=[col])
        r1 = stats.pearsonr(d[col], d.win_pct); r2 = stats.pearsonr(d.dropna(subset=["sp_rank"])[col], d.dropna(subset=["sp_rank"]).sp_rank)
        res_rows.append((lag, len(d), r1[0], r1[1], len(d.dropna(subset=["sp_rank"])), r2[0], r2[1]))
    out += ["| Lag | n (win%) | r(class rank, win%) | p | n (SP+) | r(class rank, SP+ rank) | p |", "|---|---|---|---|---|---|---|"]
    for lag, n1, r1, p1, n2, r2, p2 in res_rows:
        out.append(f"| {lag} yr | {n1} | {r1:+.2f} (R²={r1**2:.2f}) | {p1:.3f} | {n2} | {r2:+.2f} (R²={r2**2:.2f}) | {p2:.3f} |")
    d3 = q6.dropna(subset=["rank_247_composite_lag3"])
    slope, intercept, rv, pv, se = stats.linregress(d3.rank_247_composite_lag3, d3.win_pct)
    d3 = d3.assign(pred=intercept + slope * d3.rank_247_composite_lag3, resid=lambda x: x.win_pct - x.pred)
    out += ["", f"Fit (lag 3): win% = {intercept:.3f} {slope:+.4f} × class rank (R² = {rv**2:.2f}, n = {len(d3)}). Residual = actual − predicted win%:", "",
            "| Era | n | mean 247 rank (lag 3) | mean residual (win%) | read |", "|---|---|---|---|---|"]
    for era in fl.ERA_ORDER:
        e = d3[d3.era == era]
        if len(e):
            out.append(f"| {era} | {len(e)} | {e.rank_247_composite_lag3.mean():.1f} | {e.resid.mean():+.3f} | "
                       f"{'over-performs talent' if e.resid.mean() > 0.02 else ('under-performs talent' if e.resid.mean() < -0.02 else 'in line with talent')} |")
    out += ["", f"_The lag-3 slope is {'wrong-signed (better classes → lower win%)' if slope > 0 else 'correctly signed'} and not significant (p = {pv:.2f}); "
            "the residuals above are therefore effectively each era's win% minus the window mean, not a talent-adjusted verdict. "
            "Read them as descriptive only._",
            "", "_Caveat: 247 Composite ranks for 2002-2009 classes are retroactive reconstructions (247Sports launched 2010) and 247 "
            "re-rates classes after the cycle; the 2022-23 classes carry CONFLICTING signing-day vs current ranks (see recruiting_football.csv notes). "
            "OU's classes sit in a narrow #3-#19 band, which compresses the explanatory range._", ""]

    # ------------------------------------------------------------ Q7 luck
    out += ["## Q7 — Luck vs skill", "",
            f"Pythagorean expectation uses exponent {fl.PYTHAG_EXP}: expW = G × PF^e / (PF^e + PA^e).", "",
            "| Era | Actual W | Pythag W | Luck (W − exp) | Luck per season | One-score record | One-score win% |", "|---|---|---|---|---|---|---|"]
    for era in fl.ERA_ORDER:
        s = seasons[seasons.era == era]; g = games[(games.era == era) & (games.one_score == "Y")]
        w, l, p = rec(g)
        out.append(f"| {era} | {s.W.sum()} | {s.pythag_w.sum():.1f} | {s.luck_w.sum():+.1f} | {s.luck_w.mean():+.2f} | {w}-{l} | {p:.3f} |")
    top = seasons.reindex(seasons.luck_w.abs().sort_values(ascending=False).index).head(5)
    out += ["", "Largest single-season gaps (actual − Pythagorean):", ""]
    for r in top.itertuples():
        out.append(f"- {r.season} ({r.era}): {r.W}-{r.L}, expected {r.pythag_w:.1f} W → **{r.luck_w:+.1f}**")
    # year-over-year regression of margin/G
    m = seasons.set_index("season").margin_pg
    yoy = pd.DataFrame({"this": m, "next": m.shift(-1)}).dropna()
    rho = stats.pearsonr(yoy.this, yoy.next)
    lk = seasons.set_index("season").luck_w
    lk2 = pd.DataFrame({"this": lk, "next": lk.shift(-1)}).dropna()
    rho2 = stats.pearsonr(lk2.this, lk2.next)
    out += ["", f"- Year-over-year persistence of margin/G: r = {rho[0]:+.2f} (n = {len(yoy)}, p = {rho[1]:.3f}) — weakly positive, not significant at this n; OU's season-to-season strength is only loosely persistent.",
            f"- Year-over-year persistence of luck (W − Pythag): r = {rho2[0]:+.2f} (n = {len(lk2)}, p = {rho2[1]:.3f}) — no persistence; luck mean-reverts.",
            f"- 2025 luck: {float(seasons[seasons.season==2025].luck_w.iloc[0]):+.1f} W vs Pythagorean; one-score record "
            f"{fmt_rec(games[(games.season==2025)&(games.one_score=='Y')])}. 2024: {float(seasons[seasons.season==2024].luck_w.iloc[0]):+.1f}; "
            f"one-score {fmt_rec(games[(games.season==2024)&(games.one_score=='Y')])}.", ""]

    # ------------------------------------------------------------ Q8 robustness
    rng = np.random.default_rng(20260907)
    out += ["## Q8 — Robustness checks", "",
            "### Pythagorean exponent sensitivity (era luck = actual W − expected W)", "",
            "| Era | e = 2.0 | e = 2.37 (used) | e = 2.7 | e = 3.0 |", "|---|---|---|---|---|"]
    for era in fl.ERA_ORDER:
        s = seasons[seasons.era == era]
        cells = []
        for e in (2.0, 2.37, 2.7, 3.0):
            exp = sum(fl.pythagorean_wins(r.PF, r.PA, r.G, e) for r in s.itertuples())
            cells.append(f"{s.W.sum() - exp:+.1f}")
        out.append(f"| {era} | " + " | ".join(cells) + " |")
    out += ["", "### One-score threshold sensitivity (record in close games)", "",
            "| Era | ≤3 pts | ≤7 pts | ≤8 pts (used) | ≤10 pts |", "|---|---|---|---|---|"]
    for era in fl.ERA_ORDER:
        g = games[games.era == era]
        cells = [fmt_rec(g[g.margin.abs() <= t]) for t in (3, 7, 8, 10)]
        out.append(f"| {era} | " + " | ".join(cells) + " |")
    out += ["", "### Bootstrap 95% intervals (game-level resampling, 5,000 draws, seed 20260907)", "",
            "| Quantity | Point estimate | 95% interval | n games |", "|---|---|---|---|"]
    for era in fl.ERA_ORDER:
        g = games[games.era == era]
        wins = (g.result == "W").values.astype(float)
        boots = [rng.choice(wins, len(wins), replace=True).mean() for _ in range(5000)]
        lo, hi = np.percentile(boots, [2.5, 97.5])
        out.append(f"| {era} win% | {wins.mean():.3f} | {lo:.3f}–{hi:.3f} | {len(wins)} |")
    m_b, m_s = gb.margin.values.astype(float), gs.margin.values.astype(float)
    diffs = [rng.choice(m_s, len(m_s)).mean() - rng.choice(m_b, len(m_b)).mean() for _ in range(5000)]
    lo, hi = np.percentile(diffs, [2.5, 97.5])
    out.append(f"| Margin/G, SEC 2024-25 minus Big 12 2021-23 | {m_s.mean() - m_b.mean():+.1f} | {lo:+.1f} to {hi:+.1f} | {len(m_s)} vs {len(m_b)} |")
    one_v = games[(games.era == "Venables") & (games.one_score == "Y")]; one_r = games[(games.era == "Riley") & (games.one_score == "Y")]
    for name, g in (("Riley one-score win%", one_r), ("Venables one-score win%", one_v)):
        wins = (g.result == "W").values.astype(float)
        boots = [rng.choice(wins, len(wins), replace=True).mean() for _ in range(5000)]
        lo, hi = np.percentile(boots, [2.5, 97.5])
        out.append(f"| {name} | {wins.mean():.3f} | {lo:.3f}–{hi:.3f} | {len(wins)} |")
    out += ["", "_Read: **Riley's positive and Venables' negative luck survive every exponent and every close-game threshold.** "
            "**Stoops' luck does not** — it swings from +6.2 to −13.0 across exponents (238 games, so a tiny per-game bias in the "
            "exponent compounds), which means the Stoops figure and any 27-season 'total luck' number are exponent artefacts and "
            "should be read as ≈0. The Riley/Venables one-score gap is large but its bootstrap intervals overlap (n = 27 vs 19), "
            "and the raw SEC-era margin drop's interval crosses zero at the game level (26 vs 39 games) — so Q3 and the close-game "
            "contrast are directionally supported, not statistically tight: MEDIUM confidence._", ""]

    # ------------------------------------------------------------ coaches
    out += ["## Coach records (coaches_football.csv)", "", "| Coach | Tenure | W-L | Conf titles | CFP apps | BCS/CFP title games | Natl titles |", "|---|---|---|---|---|---|---|"]
    for c in coaches.itertuples():
        out.append(f"| {c.coach} | {c.tenure_start}-{c.tenure_end} | {c.ou_wins}-{c.ou_losses} | {c.conf_titles} | {c.cfp_appearances} | {c.bcs_or_cfp_title_games} | {c.national_titles} |")
    out.append("")
    (DATA / "football_analysis_output.md").write_text("\n".join(out) + "\n", encoding="utf-8")

    # ================================================================ CHARTS
    CHARTS.mkdir(exist_ok=True)
    yrs = seasons.season.values
    # 01 win% + margin/G
    fig, ax = plt.subplots(figsize=(13, 5.5))
    ax.bar(yrs, seasons.win_pct, color=[ERA_COLOR[e] for e in seasons.era], alpha=0.85, label="Win %")
    ax.set_ylim(0, 1.08); ax.set_ylabel("Win %")
    ax2 = ax.twinx(); ax2.plot(yrs, seasons.margin_pg, "-o", color=DARK, lw=1.8, ms=4, label="Margin / game"); ax2.set_ylabel("Point margin per game"); ax2.grid(False)
    ax2.axhline(0, color=DARK, lw=0.6)
    era_vlines(ax); era_shade(ax, yrs)
    ax.set_xticks(yrs); ax.set_xticklabels(yrs, rotation=90, fontsize=8)
    ax.set_title("Oklahoma has had exactly two losing seasons since 1999 — both under Venables (2022, 2024), both followed by 10-3")
    ax.legend(loc="lower left", fontsize=8); ax2.legend(loc="lower right", fontsize=8)
    footer(fig, "Bars = win% (colour = era). Line = point margin per game (right axis; dual axis justified: same seasons, two units). Source: games_football.csv (Wikipedia season articles) [CONFIRMED]. n = 27 seasons.")
    fig.savefig(CHARTS / "01_winpct_margin_by_era.png"); plt.close(fig)

    # 02 SP+ offense vs defense rank scatter
    fig, ax = plt.subplots(figsize=(8.5, 7))
    for era in fl.ERA_ORDER:
        e = rt[rt.era == era]
        ax.scatter(e.sp_off_rank, e.sp_def_rank, s=70, color=ERA_COLOR[era], label=era, edgecolor="white", zorder=3)
        for r in e.itertuples():
            ax.annotate(str(r.season), (r.sp_off_rank, r.sp_def_rank), textcoords="offset points", xytext=(4, 4), fontsize=7.5)
    ax.set_xlim(0, 90); ax.set_ylim(0, 90); ax.invert_xaxis(); ax.invert_yaxis()
    ax.axvline(25, color=GRAY, ls=":"); ax.axhline(25, color=GRAY, ls=":")
    # axes are inverted: top-right (small x, small y) = elite at both
    ax.text(1, 1.5, "elite both", fontsize=9, color=GRAY, ha="right", va="top")
    ax.text(89, 1.5, "elite defense, weak offense", fontsize=9, color=GRAY, ha="left", va="top")
    ax.text(89, 89, "weak both", fontsize=9, color=GRAY, ha="left", va="bottom")
    ax.text(1, 89, "elite offense, weak defense", fontsize=9, color=GRAY, ha="right", va="bottom")
    ax.set_xlabel("SP+ offense rank (better →)"); ax.set_ylabel("SP+ defense rank (better ↑)")
    rd = rt[rt.era == "Riley"].sp_def_rank
    ax.set_title(f"Riley's OU was the most lopsided team in the window: top-3 offenses over "
                 f"#{int(rd.min())}-#{int(rd.max())} defenses (four of five seasons #43 or worse)")
    ax.legend(loc="center left")
    footer(fig, "SP+ = opponent/tempo-adjusted (Connelly). 2005-18 Football Outsiders archive; 2019-25 ESPN/puntandrally reprints; 2020-22 off/def ranks derived from full rating lists. [REPORTED/ESTIMATED] n = 21.")
    fig.savefig(CHARTS / "02_sp_offense_vs_defense.png"); plt.close(fig)

    # 03 national rank over time (SP+ off/def + ESPN eff dashed)
    fig, ax = plt.subplots(figsize=(13, 5.5))
    ax.plot(rt.season, rt.sp_off_rank, "-o", color=CRIMSON, lw=2, ms=5, label="SP+ offense rank")
    ax.plot(rt.season, rt.sp_def_rank, "-s", color=BLUE, lw=2, ms=5, label="SP+ defense rank")
    ax.plot(rt.season, rt.eff_off_rank, ":", color=CRIMSON, lw=1.2, alpha=0.7, label="ESPN offense eff. rank")
    ax.plot(rt.season, rt.eff_def_rank, ":", color=BLUE, lw=1.2, alpha=0.7, label="ESPN defense eff. rank")
    ax.set_ylim(100, 0); ax.set_ylabel("National rank (1 = best)"); era_vlines(ax); era_shade(ax, rt.season.values)
    ax.set_xticks(rt.season); ax.set_xticklabels(rt.season, rotation=90, fontsize=8)
    ax.set_title("The units swapped: Riley's #1 offenses vs Venables' rebuilt defense (#65 → #4) with a collapsed offense")
    ax.legend(loc="lower left", fontsize=8, ncol=2)
    footer(fig, "Solid = SP+ (Connelly), dotted = ESPN Power Index efficiency ranks. Two independent systems agree on the shape. [REPORTED] n = 21 seasons (2005-25).")
    fig.savefig(CHARTS / "03_unit_ranks_over_time.png"); plt.close(fig)

    # 04 SOS distribution Big 12 vs SEC
    fig, ax = plt.subplots(figsize=(9, 5.5))
    b12 = rt[rt.conference == "Big 12"]; secc = rt[rt.conference == "SEC"]
    ax.boxplot([b12.sos_rank, secc.sos_rank], tick_labels=[f"Big 12 (2005-23, n={len(b12)})", f"SEC (2024-25, n={len(secc)})"], widths=0.5,
               medianprops=dict(color=DARK), boxprops=dict(color=GRAY))
    for i, d in enumerate([b12, secc], 1):
        jitter = np.linspace(-0.12, 0.12, len(d))
        ax.scatter(i + jitter, d.sos_rank, color=[ERA_COLOR[e] for e in d.era], s=55, zorder=3, edgecolor="white")
        for r, j in zip(d.itertuples(), jitter):
            if r.season >= 2021:
                ax.annotate(str(r.season), (i + j, r.sos_rank), textcoords="offset points", xytext=(6, -3), fontsize=8)
    ax.set_ylim(60, 0); ax.set_ylabel("ESPN strength-of-schedule rank (1 = hardest)")
    harder24 = int((b12.sos_rank < float(secc[secc.season == 2024].sos_rank.iloc[0])).sum())
    harder25 = int((b12.sos_rank < float(secc[secc.season == 2025].sos_rank.iloc[0])).sum())
    ax.set_title(f"Only {harder24} of OU's {len(b12)} Big 12 schedules were harder than 2024's SEC slate (#{int(secc[secc.season==2024].sos_rank.iloc[0])}); "
                 f"{harder25} were harder than 2025's (#{int(secc[secc.season==2025].sos_rank.iloc[0])})")
    footer(fig, "ESPN Power Index 'AVG SOS' rank, end of season. Dots coloured by era. SEC n = 2 — small sample. [REPORTED]")
    fig.savefig(CHARTS / "04_sos_big12_vs_sec.png"); plt.close(fig)

    # 05 actual vs pythagorean
    fig, ax = plt.subplots(figsize=(13, 5.5))
    ax.bar(yrs - 0.2, seasons.W, width=0.4, color=CRIMSON, label="Actual wins")
    ax.bar(yrs + 0.2, seasons.pythag_w, width=0.4, color=GRAY, label="Pythagorean expected wins")
    for r in seasons.itertuples():
        ax.text(r.season, max(r.W, r.pythag_w) + 0.25, f"{r.luck_w:+.1f}", ha="center", fontsize=7, color=CRIMSON if r.luck_w > 0 else BLUE)
    ax.set_ylim(0, 15.5); ax.set_ylabel("Wins"); era_vlines(ax); era_shade(ax, yrs)
    ax.set_xticks(yrs); ax.set_xticklabels(yrs, rotation=90, fontsize=8); ax.legend(loc="upper left", fontsize=8)
    lr = float(seasons[seasons.era == "Riley"].luck_w.sum()); lv = float(seasons[seasons.era == "Venables"].luck_w.sum())
    ax.set_title(f"Riley's teams beat Pythagorean expectation by {lr:.1f} wins, Venables' fall {abs(lv):.1f} short; "
                 f"2025 was {float(seasons[seasons.season==2025].luck_w.iloc[0]):+.1f}")
    footer(fig, f"Pythagorean expectation, exponent {fl.PYTHAG_EXP}; annotation = actual − expected. Riley/Venables signs hold for exponents 2.0–3.0; the Stoops-era total does not (see Q8). [ESTIMATED]")
    fig.savefig(CHARTS / "05_actual_vs_pythagorean.png"); plt.close(fig)

    # 06 recruiting lag-3 vs win%
    fig, ax = plt.subplots(figsize=(8.5, 6.5))
    for era in fl.ERA_ORDER:
        e = d3[d3.era == era]
        ax.scatter(e.rank_247_composite_lag3, e.win_pct, s=70, color=ERA_COLOR[era], label=era, edgecolor="white", zorder=3)
        for r in e.itertuples():
            ax.annotate(str(r.season), (r.rank_247_composite_lag3, r.win_pct), textcoords="offset points", xytext=(4, 4), fontsize=7.5)
    xs = np.linspace(d3.rank_247_composite_lag3.min(), d3.rank_247_composite_lag3.max(), 50)
    ax.plot(xs, intercept + slope * xs, color=DARK, lw=1.5, ls="--", label=f"fit (R² = {rv**2:.2f}, n = {len(d3)})")
    ax.set_xlabel("247 Composite class rank, signed 3 seasons earlier (lower = better)"); ax.set_ylabel("Season win %")
    ax.set_title(f"Recruiting rank explains little of OU's year-to-year variance (R² = {rv**2:.2f}): the classes are always top-20")
    ax.legend(loc="lower right", fontsize=8)
    footer(fig, "247Sports Composite team rank (2002-09 retroactive); win% from games_football.csv. Lag 3 = class of Y joined to season Y+3. [CONFIRMED ranks / ESTIMATED fit]")
    fig.savefig(CHARTS / "06_recruiting_vs_winpct.png"); plt.close(fig)

    # 07 Red River timeline
    rr_g = games[games.opponent == "Texas"].sort_values("date")
    fig, ax = plt.subplots(figsize=(13, 5))
    cols = [CRIMSON if m > 0 else ORANGE for m in rr_g.margin]
    xl = [f"{r.season}{'*' if r.game_type == 'CCG' else ''}" for r in rr_g.itertuples()]
    ax.bar(range(len(rr_g)), rr_g.margin, color=cols)
    ax.axhline(0, color=DARK, lw=0.8); ax.set_xticks(range(len(rr_g))); ax.set_xticklabels(xl, rotation=90, fontsize=8)
    for i, r in enumerate(rr_g.itertuples()):
        ax.text(i, r.margin + (1.2 if r.margin > 0 else -3.2), f"{r.ou_pts}-{r.opp_pts}", ha="center", fontsize=6.5)
    w, l, p = rec(rr_g)
    ax.set_ylabel("OU margin (points)")
    vg = rr_g[rr_g.era == "Venables"]
    ax.set_title(f"Red River 1999-2025: OU {w}-{l} overall, but {fmt_rec(vg)} under Venables (lost {int((vg.result=='L').sum())} of {len(vg)})")
    footer(fig, "Crimson = OU win, orange = Texas win. * = 2018 Big 12 Championship Game (second meeting that season). Source: games_football.csv [CONFIRMED]. n = 28.")
    fig.savefig(CHARTS / "07_red_river_timeline.png"); plt.close(fig)

    # 08 one-score record by era
    fig, ax = plt.subplots(figsize=(8.5, 5.2))
    labels, vals, ns = [], [], []
    for era in fl.ERA_ORDER:
        g = games[(games.era == era) & (games.one_score == "Y")]
        w, l, p = rec(g); labels.append(f"{era}\n{w}-{l}"); vals.append(p); ns.append(w + l)
    bars = ax.bar(labels, vals, color=[ERA_COLOR[e] for e in fl.ERA_ORDER])
    for b, n in zip(bars, ns):
        ax.text(b.get_x() + b.get_width() / 2, b.get_height() + 0.01, f"n = {n}", ha="center", fontsize=9)
    ax.axhline(0.5, color=GRAY, ls=":"); ax.set_ylim(0, 1); ax.set_ylabel("Win % in one-score games (≤ 8 pts)")
    allg = games[games.one_score == "Y"]
    ax.set_title(f"Close games: OU is {fmt_rec(allg)} in one-score games since 1999 — Venables' teams are {fmt_rec(allg[allg.era=='Venables'])}")
    footer(fig, "One-score = final margin within 8 points. Source: games_football.csv [CONFIRMED]; win% is ESTIMATED-derived.")
    fig.savefig(CHARTS / "08_one_score_by_era.png"); plt.close(fig)

    # 09 EPA unit ranks — an independent third system
    if epa is not None and len(epa):
        fig, ax = plt.subplots(figsize=(10, 5.5))
        ax.plot(epa.season, epa.off_epa_rank, "-o", color=CRIMSON, lw=2.4, ms=8, label="Offense EPA/play rank")
        ax.plot(epa.season, epa.def_epa_rank, "-s", color=BLUE, lw=2.4, ms=8, label="Defense EPA/play rank")
        for r in epa.itertuples():
            ax.annotate(f"#{int(r.off_epa_rank)}", (r.season, r.off_epa_rank), textcoords="offset points",
                        xytext=(0, -16), ha="center", fontsize=8.5, color=CRIMSON, fontweight="bold")
            ax.annotate(f"#{int(r.def_epa_rank)}", (r.season, r.def_epa_rank), textcoords="offset points",
                        xytext=(0, 10), ha="center", fontsize=8.5, color=BLUE, fontweight="bold")
        ax.axvline(2021.5, color=DARK, ls="--", lw=1, alpha=0.6)
        ax.text(2021.45, 5, "Riley", ha="right", fontsize=9, color=ORANGE, fontweight="bold")
        ax.text(2021.55, 5, "Venables", ha="left", fontsize=9, color=CRIMSON, fontweight="bold")
        ax.set_ylim(int(epa[["off_epa_rank", "def_epa_rank"]].max().max()) + 18, 0)
        ax.set_xticks(epa.season); ax.set_ylabel("National rank (1 = best)")
        ax.set_title("A third, independent system shows the same swap: play-level EPA, 2021-2025")
        ax.legend(loc="lower left", fontsize=9)
        footer(fig, "EPA per play from sportsdataverse ESPN play-by-play release assets (no API key). "
                    "NOT opponent-adjusted, so OU's offense ranks below its SP+ rank while playing a top-15 schedule. [REPORTED]")
        fig.savefig(CHARTS / "09_epa_unit_ranks.png"); plt.close(fig)

    print(f"wrote {DATA / 'football_analysis_output.md'} and {len(list(CHARTS.glob('*.png')))} charts to {CHARTS}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
