#!/usr/bin/env python3
"""
championship_analysis.py — Phase 11: compare 2026 Oklahoma to NCAA national champions.

Computes (no hand math, fully reproducible):
  - Derived metrics (win%, OPS, ISO, R/G, run-diff/G, HR/G, WHIP, K/9, BB/9, E/G).
  - "Typical champion" baselines (mean/median/std/percentiles) for three reference
    sets: ALL champions, MODERN (2010-2025), and FLAT-SEAM era (2015-2025, the bat
    environment most comparable to 2026).
  - OU z-scores vs the modern champion baseline.
  - Similarity: standardized Euclidean distance (nearest-champion ranking) and a
    regularized Mahalanobis distance on a reduced feature set (caveated; small n).
  - A "strength composite" percentile: % of champions statistically weaker than OU.

Writes charts 11-15 and data/championship_analysis_output.md. No network; no fabrication.
Cells that are blank in champions.csv are treated as missing (NaN), never imputed silently.
"""
from __future__ import annotations
import math
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
CHARTS = ROOT / "charts"
CRIMSON, GRAY, GOLD, DARK = "#841617", "#8a8d8f", "#C9A227", "#2b2b2b"
plt.rcParams.update({"figure.dpi": 150, "savefig.bbox": "tight",
                     "savefig.facecolor": "white", "axes.grid": True,
                     "grid.color": "#e9e9e9", "axes.titleweight": "bold"})


def parse_ip(v):
    """Convert baseball IP notation (e.g. 549.2 = 549 + 2/3) to real innings."""
    if pd.isna(v) or str(v).strip() == "":
        return np.nan
    f = float(v)
    whole = int(f)
    frac = round((f - whole) * 10)
    return whole + frac / 3.0


def load():
    df = pd.read_csv(DATA / "champions.csv")
    num = ["W", "L", "T", "G", "R", "RA", "AVG", "OBP", "SLG", "HR", "ERA",
           "H_allowed", "BB_allowed", "K_pitch", "opp_AVG", "FLD_pct", "E", "DP", "rpi"]
    for c in num:
        df[c] = pd.to_numeric(df[c], errors="coerce")
    df["IP_real"] = df["IP"].apply(parse_ip)
    df["win_pct"] = (df["W"] + 0.5 * df["T"]) / (df["W"] + df["L"] + df["T"])
    df["OPS"] = df["OBP"] + df["SLG"]
    df["ISO"] = df["SLG"] - df["AVG"]
    df["R_per_G"] = df["R"] / df["G"]
    df["RA_per_G"] = df["RA"] / df["G"]
    df["run_diff"] = df["R"] - df["RA"]
    df["run_diff_pg"] = df["run_diff"] / df["G"]
    df["HR_per_G"] = df["HR"] / df["G"]
    df["WHIP"] = (df["H_allowed"] + df["BB_allowed"]) / df["IP_real"]
    df["K9"] = df["K_pitch"] * 9 / df["IP_real"]
    df["BB9"] = df["BB_allowed"] * 9 / df["IP_real"]
    df["E_per_G"] = df["E"] / df["G"]
    return df


def fmt(x, p=3):
    return "NF" if pd.isna(x) else f"{x:.{p}f}"


def baseline_table(champs, metrics, label):
    lines = [f"### Typical champion baseline — {label} (n={len(champs)})\n",
             "| Metric | Mean | Median | Std | P25 | P75 | OU 2026 |",
             "|---|---|---|---|---|---|---|"]
    return lines, champs


def main() -> int:
    df = load()
    ou = df[df.status == "CHAMPION-SUBJECT"].iloc[0]
    champs_all = df[df.status == "CHAMPION"].copy()
    champs_modern = champs_all[champs_all.year >= 2010].copy()
    champs_flat = champs_all[champs_all.year >= 2015].copy()

    metrics = [("win_pct", 3, "+"), ("R_per_G", 2, "+"), ("run_diff_pg", 2, "+"),
               ("AVG", 3, "+"), ("OBP", 3, "+"), ("SLG", 3, "+"), ("OPS", 3, "+"),
               ("HR_per_G", 2, "+"), ("ERA", 2, "-"), ("WHIP", 2, "-"),
               ("K9", 1, "+"), ("BB9", 1, "-"), ("opp_AVG", 3, "-"),
               ("FLD_pct", 3, "+"), ("E_per_G", 2, "-")]

    out = ["# Phase 11 — Championship Comparison: Computed Results",
           "",
           "_Generated by `scripts/championship_analysis.py` from `data/champions.csv`. "
           "All figures computed, not hand-entered. n excludes 2012 Arizona where a metric is missing._",
           ""]

    # ---- Baselines (three reference sets) ----
    for champs, label in [(champs_all, "ALL champions 2000-2025"),
                          (champs_modern, "MODERN 2010-2025"),
                          (champs_flat, "FLAT-SEAM era 2015-2025")]:
        out.append(f"## Typical champion baseline — {label} (n={len(champs)})\n")
        out.append("| Metric | Mean | Median | Std | P25 | P75 | **OU 2026** | OU vs mean |")
        out.append("|---|---|---|---|---|---|---|---|")
        for m, p, good in metrics:
            s = champs[m].dropna()
            ouv = ou[m]
            delta = ouv - s.mean()
            arrow = "▲" if ((delta > 0) == (good == "+")) else "▼"
            out.append(f"| {m} | {fmt(s.mean(),p)} | {fmt(s.median(),p)} | {fmt(s.std(),p)} "
                       f"| {fmt(s.quantile(.25),p)} | {fmt(s.quantile(.75),p)} "
                       f"| **{fmt(ouv,p)}** | {arrow} {fmt(delta,p)} |")
        out.append("")

    # ---- OU z-scores vs MODERN champions ----
    out.append("## OU z-scores vs. MODERN champions (2010-2025)\n")
    out.append("Positive z = OU above the champion mean. 'Strength' orients so + is better.\n")
    out.append("| Metric | OU | Champ mean | Champ std | z (raw) | Strength read |")
    out.append("|---|---|---|---|---|---|")
    z_rows = {}
    for m, p, good in metrics:
        s = champs_modern[m].dropna()
        mu, sd = s.mean(), s.std()
        z = (ou[m] - mu) / sd if sd else np.nan
        z_rows[m] = z
        strength_z = z if good == "+" else -z
        if pd.isna(strength_z):
            read = "n/a"
        elif strength_z > 0.5:
            read = "ABOVE typical champ"
        elif strength_z < -0.5:
            read = "BELOW typical champ"
        else:
            read = "≈ typical champ"
        out.append(f"| {m} | {fmt(ou[m],p)} | {fmt(mu,p)} | {fmt(sd,p)} | {fmt(z,2)} | {read} |")
    out.append("")

    # ---- Similarity: standardized Euclidean distance to each champion ----
    feats = ["win_pct", "OBP", "SLG", "HR_per_G", "ERA", "K9", "FLD_pct"]
    pool = champs_all.dropna(subset=feats).copy()  # drops 2012 Arizona
    mu = pool[feats].mean()
    sd = pool[feats].std()
    Z = (pool[feats].astype(float) - mu) / sd
    ouz = (ou[feats].astype(float) - mu) / sd
    pool["dist"] = np.sqrt(((Z - ouz) ** 2).sum(axis=1).astype(float))
    pool_sorted = pool.sort_values("dist")
    out.append("## Championship similarity — standardized Euclidean distance to OU 2026\n")
    out.append(f"Feature space (7, standardized on champion pop.): {', '.join(feats)}. "
               f"Lower = more similar. 2012 Arizona dropped (incomplete).\n")
    out.append("| Rank | Champion | Distance | Note |")
    out.append("|---|---|---|---|")
    for i, (_, r) in enumerate(pool_sorted.iterrows(), 1):
        note = ""
        if i == 1:
            note = "CLOSEST MATCH"
        elif i == len(pool_sorted):
            note = "LEAST SIMILAR"
        out.append(f"| {i} | {int(r.year)} {r.team} | {r.dist:.2f} | {note} |")
    out.append("")

    # ---- Mahalanobis (reduced features, regularized; caveated) ----
    mfeats = ["win_pct", "OPS", "ERA", "FLD_pct"]
    mp = champs_all.dropna(subset=mfeats).copy()
    X = mp[mfeats].to_numpy(dtype=float)
    cov = np.cov(X, rowvar=False)
    cov_reg = cov + np.eye(len(mfeats)) * 1e-6  # regularize
    inv = np.linalg.pinv(cov_reg)
    cmean = X.mean(axis=0)
    ouvec = ou[mfeats].to_numpy(dtype=float)
    d_ou = math.sqrt((ouvec - cmean) @ inv @ (ouvec - cmean))
    md = []
    for _, r in mp.iterrows():
        v = r[mfeats].to_numpy(dtype=float)
        md.append((r.year, r.team, math.sqrt((v - cmean) @ inv @ (v - cmean))))
    md_mean = np.mean([m[2] for m in md])
    out.append("## Mahalanobis distance to the champion centroid (reduced 4-feature set)\n")
    out.append(f"Features: {', '.join(mfeats)}. **Caveat:** n={len(mp)} with correlated "
               f"features makes the covariance estimate fragile — read as indicative, not precise.\n")
    out.append(f"- OU Mahalanobis distance to champion centroid: **{d_ou:.2f}**")
    out.append(f"- Champion mean distance to their own centroid: **{md_mean:.2f}** "
               f"(OU is {'more' if d_ou > md_mean else 'less'} typical-distance than the average champion)\n")

    # ---- Strength composite + percentile ----
    comp_feats = [(m, good) for m, p, good in metrics
                  if m in ("win_pct", "OBP", "SLG", "ERA", "K9", "FLD_pct",
                           "run_diff_pg", "opp_AVG", "HR_per_G")]
    cpool = champs_all.copy()

    def composite(feature_list):
        pool2 = cpool.dropna(subset=[m for m, _ in feature_list]).copy()
        mu2 = pool2[[m for m, _ in feature_list]].mean()
        sd2 = pool2[[m for m, _ in feature_list]].std()
        def score(row):
            tot = 0.0
            for m, good in feature_list:
                z = (row[m] - mu2[m]) / sd2[m]
                tot += z if good == "+" else -z
            return tot / len(feature_list)
        pool2["composite"] = pool2.apply(score, axis=1)
        ou_score = score(ou)
        weaker = (pool2["composite"] < ou_score).sum()
        pct = 100 * weaker / len(pool2)
        return pool2, ou_score, pct

    pool_full, ou_full, pct_full = composite(comp_feats)
    pool_nohr, ou_nohr, pct_nohr = composite([(m, g) for m, g in comp_feats if m != "HR_per_G"])
    out.append("## Championship 'strength composite' percentile\n")
    out.append("Composite = mean of strength-oriented z-scores across features "
               "(ERA/opp_AVG sign-flipped so higher = stronger). Standardized on champions.\n")
    out.append(f"- **Including HR/G:** OU composite {ou_full:+.2f}; "
               f"**{pct_full:.0f}% of champions were statistically weaker than OU.**")
    out.append(f"- **Excluding HR/G (era-neutral):** OU composite {ou_nohr:+.2f}; "
               f"**{pct_nohr:.0f}% of champions were statistically weaker than OU.**")
    out.append(f"- Reading: OU sits in the **{'lower' if pct_full < 50 else 'upper'} half** of the "
               f"champion strength distribution{' (and lower with HR removed)' if pct_nohr < pct_full else ''}.\n")

    # ---- HR era note ----
    out.append("## Home-run era context\n")
    out.append(f"- OU 2026 HR/G: **{ou.HR_per_G:.2f}** (full season, 93 HR / 64 G).")
    out.append(f"- FLAT-SEAM era champion HR/G mean (2015-2025): **{champs_flat.HR_per_G.mean():.2f}**.")
    out.append(f"- Dead-bat era low: 2013 UCLA **{df[(df.year==2013)].HR_per_G.iloc[0]:.2f}** HR/G.")
    out.append(f"- Modern power champ high: 2024 Tennessee **{df[(df.year==2024)].HR_per_G.iloc[0]:.2f}** HR/G.")
    out.append("- OU's *regular-season* HR/G is league-average for a flat-seam champion; the story "
               "is the **postseason surge** (26 HR in the first 10 NCAA Tournament games [REPORTED]).\n")

    (DATA / "championship_analysis_output.md").write_text("\n".join(out) + "\n")

    # ============================ CHARTS ============================
    # 11 — HR/G by champion (era timeline), OU highlighted
    d2 = df.dropna(subset=["HR_per_G"]).sort_values("year")
    fig, ax = plt.subplots(figsize=(12, 5.5))
    colors = [CRIMSON if r.status == "CHAMPION-SUBJECT" else GRAY for _, r in d2.iterrows()]
    ax.bar([f"{int(r.year)}\n{r.team.split()[0]}" for _, r in d2.iterrows()],
           d2.HR_per_G, color=colors)
    ax.axhline(champs_flat.HR_per_G.mean(), color=GOLD, ls="--", lw=1.5,
               label=f"2015-25 champ mean ({champs_flat.HR_per_G.mean():.2f})")
    ax.set_ylabel("Home runs per game")
    ax.set_title("HR/Game: 2026 Oklahoma (crimson) vs. National Champions — Mind the Bat Eras")
    ax.tick_params(axis="x", labelsize=7)
    ax.legend()
    fig.text(0.5, -0.04, "Pre-BBCOR (2010), dead-bat (2011-14), flat-seam ball (2015+) are different HR environments. "
             "Source: champions.csv. [CONFIRMED/REPORTED]", ha="center", fontsize=8, style="italic", color="#666")
    fig.savefig(CHARTS / "11_hr_era_timeline.png")
    plt.close(fig)

    # 12 — Radar: OU vs typical (modern) champion (percentile-normalized)
    radar_m = ["win_pct", "OBP", "SLG", "HR_per_G", "K9", "FLD_pct"]
    inv_m = []  # all higher=better here
    cm = champs_modern
    def pctile(series, val):
        s = series.dropna()
        return 100 * (s < val).mean()
    ou_pct = [pctile(cm[m], ou[m]) for m in radar_m]
    typ_pct = [50] * len(radar_m)
    ang = np.linspace(0, 2 * np.pi, len(radar_m), endpoint=False).tolist()
    ou_loop = ou_pct + ou_pct[:1]; typ_loop = typ_pct + typ_pct[:1]; ang_loop = ang + ang[:1]
    fig, ax = plt.subplots(figsize=(7.5, 7.5), subplot_kw=dict(polar=True))
    ax.plot(ang_loop, ou_loop, color=CRIMSON, lw=2.5, label="OU 2026 (percentile vs champs)")
    ax.fill(ang_loop, ou_loop, color=CRIMSON, alpha=0.25)
    ax.plot(ang_loop, typ_loop, color=DARK, lw=1.5, ls="--", label="Typical champion (50th pct)")
    ax.set_xticks(ang); ax.set_xticklabels(radar_m)
    ax.set_yticks([25, 50, 75, 100]); ax.set_ylim(0, 100)
    ax.set_title("OU 2026 vs. the Typical Modern Champion (percentile rank)\n", fontsize=13)
    ax.legend(loc="upper right", bbox_to_anchor=(1.25, 1.1), fontsize=9)
    fig.savefig(CHARTS / "12_radar_vs_champion.png")
    plt.close(fig)

    # 13 — Similarity ranking (Euclidean distance)
    ps = pool_sorted.copy()
    fig, ax = plt.subplots(figsize=(9, 7))
    bars = ax.barh([f"{int(r.year)} {r.team}" for _, r in ps[::-1].iterrows()],
                   ps.dist[::-1], color=[CRIMSON if i >= len(ps)-3 else GRAY for i in range(len(ps))])
    ax.set_xlabel("Standardized Euclidean distance to OU 2026 (lower = more similar)")
    ax.set_title("Which Champions Most Resemble 2026 Oklahoma?")
    for b, v in zip(bars, ps.dist[::-1]):
        ax.text(v + 0.03, b.get_y() + b.get_height()/2, f"{v:.2f}", va="center", fontsize=8)
    fig.text(0.5, -0.03, "7 standardized features: win%, OBP, SLG, HR/G, ERA, K/9, Fld%. 2012 Arizona excluded. [computed]",
             ha="center", fontsize=8, style="italic", color="#666")
    fig.savefig(CHARTS / "13_similarity_ranking.png")
    plt.close(fig)

    # 14 — Strength composite distribution with OU marked
    pf = pool_full.sort_values("composite")
    fig, ax = plt.subplots(figsize=(11, 5.5))
    colors = [CRIMSON if r.status == "CHAMPION-SUBJECT" else GRAY for _, r in pf.iterrows()]
    ax.bar([f"{int(r.year)} {r.team.split()[0]}" for _, r in pf.iterrows()], pf.composite, color=colors)
    ax.axhline(ou_full, color=CRIMSON, ls="--", lw=1.5, label=f"OU composite ({ou_full:+.2f})")
    ax.axhline(0, color=DARK, lw=1, label="champion mean (0)")
    ax.set_ylabel("Strength composite (z, higher = stronger)")
    ax.set_title(f"Champion 'Strength Composite' — OU ranks above {pct_full:.0f}% of champions (incl. HR)")
    ax.tick_params(axis="x", labelsize=7, rotation=90)
    ax.legend()
    fig.savefig(CHARTS / "14_strength_composite.png")
    plt.close(fig)

    # 15 — OU z-score bar vs modern champs (strength-oriented)
    sm = [("win_pct","+"),("OBP","+"),("SLG","+"),("HR_per_G","+"),("run_diff_pg","+"),
          ("ERA","-"),("opp_AVG","-"),("K9","+"),("FLD_pct","+")]
    labels, vals = [], []
    for m, good in sm:
        s = champs_modern[m].dropna()
        z = (ou[m]-s.mean())/s.std()
        labels.append(m); vals.append(z if good=="+" else -z)
    fig, ax = plt.subplots(figsize=(10, 5.5))
    ax.bar(labels, vals, color=[CRIMSON if v >= 0 else GRAY for v in vals])
    ax.axhline(0, color=DARK, lw=1)
    ax.set_ylabel("Strength z-score vs modern champions (+ = better than typical champ)")
    ax.set_title("Where OU 2026 Beats or Trails the Typical Modern Champion")
    ax.tick_params(axis="x", rotation=45)
    fig.savefig(CHARTS / "15_ou_zscores.png")
    plt.close(fig)

    print("\n".join(out))
    print("\nCharts 11-15 written; results -> data/championship_analysis_output.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
